export const COLLECTIONS = {
  Users: "Users",
  Agencies: "agencies",
  SuggestedAgencies: "suggested_agencies",
  WhoRatedAgencies: "who_rated_agencies",
  AgenciesRatingInfo: "agencies_rating_info",
  News: "news",
  Bookmarks: "bookmarks",
  Comments: "comments",
  CommentsLikes: "comments_likes",
  Replies: "replies",
  ReportComments: "report_comments",
  EarlyAccess: "early_access",
  NewsCounter: "news_counter",
  DeviceTokens: "device_tokens",
  Countries: "countries",
  Lists: "lists",
  Posts: "posts",
  Contracts: "contracts",
  Jobs: "jobs",
  Notifications: "notifications",
};
